server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jta:
    enabled: true
    atomikos:
      datasource:
        maria:
          xa-data-source-class-name: org.mariadb.jdbc.MariaDbDataSource
          unique-resource-name: mariaDataSource
          max-pool-size: 2
          min-pool-size: 2
          borrow-connection-timeout: 10
          max-idle-time: 50
          test-query: 'SELECT 1'
          xa-properties:
            user:
            password:
            url: jdbc:mariadb://desktop:3306/bbi?pinGlobalTxToPhysicalConnection=true&socketTimeout=60000&sessionVariables=max_statement_time=10
          max-lifetime: 50
        pgsql:
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          unique-resource-name: pgsqlDataSource
          max-pool-size: 2
          min-pool-size: 2
          xa-properties:
            URL: jdbc:postgresql://desktop:5432/cgidis
            user:
            password:
          max-lifetime: 60
  data:
    redis:
      port: 6379
      host: desktop
      password: 12345
      database: 0
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

