server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://desktop:3306/test
    username: backendjjn
    password: 12345
    hikari:
      maximum-pool-size: 40
  data:
    redis:
      port: 6379
      host: desktop
      password: 12345
      database: 0
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

